# Generated by Django 3.1.2 on 2020-12-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20201202_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmosto',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='misuration',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='rabbocco',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='quantity',
        ),
        migrations.AddField(
            model_name='operation',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='field',
            field=models.IntegerField(default=0),
        ),
    ]
