# Generated by Django 3.1.2 on 2020-12-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20201203_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrel',
            name='name',
            field=models.IntegerField(default=0),
        ),
    ]
