# Generated by Django 3.1.2 on 2020-12-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_barrel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrel',
            name='name',
        ),
        migrations.AddField(
            model_name='barrel',
            name='pos',
            field=models.IntegerField(default=0),
        ),
    ]
