# Generated by Django 3.1.2 on 2020-12-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20201205_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='name',
            field=models.CharField(default='Operazione generica', max_length=20),
        ),
    ]
