# Generated by Django 3.1.2 on 2020-12-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_operation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(default='Prelievo', max_length=20),
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
