# Generated by Django 3.1.2 on 2020-12-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20201205_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrel',
            name='type_wood',
            field=models.CharField(choices=[('Rovere', 'Rovere'), ('Castagno', 'Castagno'), ('Frassino', 'Frassino'), ('Ginepro', 'Ginepro'), ('Ciliegio', 'Ciliegio'), ('Pero e melo', 'Pero e melo'), ('Robinia', 'Robinia'), ('Gelso', 'Gelso')], max_length=40),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=1, unique=True),
        ),
    ]
