# Generated by Django 3.1.2 on 2020-12-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20201226_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
