# Generated by Django 3.1.2 on 2021-01-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_auto_20201227_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrel',
            name='acidity',
            field=models.FloatField(default=1.0),
        ),
    ]
